# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: 🚀 Deploy the DNS records

on:
  workflow_dispatch: # manual trigger only
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options: [preview, push]
        default: push

concurrency:
  group: ${{ github.ref }}-dns
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy the DNS records
    runs-on: ubuntu-latest
    environment: DNS
    defaults: {run: {working-directory: ./dns}}
    steps:
      - uses: actions/checkout@v5
      - uses: dopplerhq/cli-action@v3
      - uses: gacts/install-dnscontrol@v1
      - name: Authorize DnsControl
        run: doppler secrets substitute ./creds.doppler.json > ./creds.json
        env: {DOPPLER_TOKEN: "${{ secrets.DOPPLER_SERVICE_TOKEN }}"}
      - run: dnscontrol ${{ inputs.action }}
      - {name: Cleanup, if: always(), run: rm -f ./creds.json}
