# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: 🚀 Deploy the DNS records

on:
  workflow_dispatch: # manual trigger only
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options: [preview, push]
        default: push

concurrency:
  group: ${{ github.ref }}-dns
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy the DNS records
    runs-on: ubuntu-latest
    environment: DNS
    defaults: {run: {working-directory: ./dns}}
    steps:
      - uses: actions/checkout@v4
      - uses: gacts/install-dnscontrol@v1
      - run: echo '{"cloudflare":{"TYPE":"CLOUDFLAREAPI","accountid":"$CF_ID","apitoken":"$CF_TOKEN"}}' > ./creds.json
      - run: dnscontrol ${{ inputs.action }}
        env:
          CF_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_TOKEN: ${{ secrets.CF_DNS_API_KEY }}
