# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: 🚀 Deploy the Terraform infrastructure

on:
  workflow_dispatch: # manual trigger only
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options: [plan, 'apply -auto-approve', 'destroy -auto-approve']
        default: plan

concurrency:
  group: ${{ github.ref }}-terraform
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy the Terraform infrastructure
    runs-on: ubuntu-latest
    environment: Terraform
    defaults: {run: {working-directory: ./terraform}}
    env: {TF_CLI_CONFIG_FILE: ./.terraformrc}
    steps:
      - uses: actions/checkout@v4
      - uses: dopplerhq/cli-action@v3
      - uses: hashicorp/setup-terraform@v3
      - name: Authorize Terraform
        run: doppler secrets substitute ./../.terraformrc.doppler.tf > $TF_CLI_CONFIG_FILE
        env: {DOPPLER_TOKEN: "${{ secrets.DOPPLER_SERVICE_TOKEN }}"}
      - run: terraform init
      - run: doppler run --name-transformer tf-var -- terraform ${{ inputs.action }}
        env: {DOPPLER_TOKEN: "${{ secrets.DOPPLER_SERVICE_TOKEN }}", TF_IN_AUTOMATION: on}
      - {name: Cleanup, if: always(), run: rm -f $TF_CLI_CONFIG_FILE}
